# files available on the cluster
OptimisedGeometry_BP0mm_2e10protons_withTimestamps_server = "/net/data_g4rt/projects/SiFiCC/InputforNN/ClusterNNOptimisedGeometry/OptimisedGeometry_BP0mm_2e10protons_withTimestamps.root"
OptimisedGeometry_BP5mm_4e9protons_withTimestamps_server = "/net/data_g4rt/projects/SiFiCC/InputforNN/ClusterNNOptimisedGeometry/OptimisedGeometry_BP5mm_4e9protons_withTimestamps.root"
OptimisedGeometry_Continuous_2e10protons_withTimestamps_server = "/net/data_g4rt/projects/SiFiCC/InputforNN/ClusterNNOptimisedGeometry/OptimisedGeometry_Continuous_2e10protons.root"
FinalDetectorVersion_RasterCoupling_OPM_38e8protons = "/net/data_g4rt/projects/SiFiCC/InputforNN/SiPMNNNewGeometry/FinalDetectorVersion_RasterCoupling_OPM_38e8protons.root"
FinalDetectorVersion_RasterCoupling_OPM_BP5mm_4e9protons = "/net/data_g4rt/projects/SiFiCC/InputforNN/SiPMNNNewGeometry/FinalDetectorVersion_RasterCoupling_OPM_BP5mm_4e9protons.root"
FinalDetectorVersion_RasterCoupling_OPM_Continuous_2e10protons = "/net/data_g4rt/projects/SiFiCC/InputforNN/SiPMNNNewGeometry/FinalDetectorVersion_RasterCoupling_OPM_Continuous_2e10protons.root"

# files local (where expected)
OptimisedGeometry_BP0mm_2e10protons_withTimestamps_local = "/root_files/OptimisedGeometry_BP0mm_2e10protons_withTimestamps.root"
OptimisedGeometry_BP5mm_4e9protons_withTimestamps_local = "/root_files/OptimisedGeometry_BP5mm_4e9protons_withTimestamps.root"
OptimisedGeometry_Continuous_2e10protons_withTimestamps_local = "/root_files/OptimisedGeometry_Continuous_2e10protons.root"
FinalDetectorVersion_RasterCoupling_OPM_38e8protons_local = "/root_files/FinalDetectorVersion_RasterCoupling_OPM_38e8protons.root"